version: '3'
services:
  mongodb:
    image: mongo:latest
  app: 
    build: .
    environment:
      - SECRET_KEY=very secret key DEV ONLY!!!
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - 3000:3000